runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.8

endpoints_api_service:
  name: venue-api.endpoints.ticket-bounty.appspot.com
  config_id: 2017-03-17r1